name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 # JDK 21 はサポートされていないので JDK 17 を指定
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt' # JDK の配布物を 'adopt' に変更

      # Docker コンテナを起動して MySQL サーバーをセットアップするための手順を追加する
      - name: Start MySQL Server
        run: docker-compose up -d
        # この手順を追加する前に適切な docker-compose.yml ファイルを提供する必要があります

      - name: Setup Gradle
        uses: gradle/setup-gradle@v4 # 最新のバージョンを使用する場合は '@v4' を削除
        with:
          gradle-version: '7.3.3' # 最新バージョンを使用する場合は '7.3.3' を削除

      - name: Build with Gradle Wrapper
        run: ./gradlew build