name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"
      - '*'

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose up For Database
        run: docker-compose up -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 8.5

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "integration"
          description: "Build GitHub Pages"
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions

